---
name: Test

on:
  pull_request:
    paths:
      - '*'
  push:
    paths:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create comment
        with:
          path: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        uses: bunysae/MQL-Compile-Action@v1.0-alpha
