---
name: Test

on:
  pull_request:
    paths:
      - '*'
  push:
    paths:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create comment
        with:
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
        uses: bunysae/MQL-Compile-Action@v1.5-alpha
