---
name: Test

on:
  pull_request:
    paths:
      - '*.js'
  push:
    paths:
      - '*.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        with:
          bot-token: ${{ secrets.GITHUB_TOKEN }}
        uses: bunysae/actions@v1.7
